(() => {
  const studioState = { kpiTiles: [], dashboards: { monthlyTrend: [], monthlyMatrix: [], performanceCoaching: [], driversSentiment: [] } };
  const colors = ["#07868b", "#e28a32", "#5a70c8", "#bd4d69", "#2d9b63", "#8b62b3", "#397d9d", "#c8a72e"];
  const viewKinds = { monthlytrendcreator: "monthlyTrend", monthlymatrixcreator: "monthlyMatrix", performancecoachingcreator: "performanceCoaching", driverssentimentcreator: "driversSentiment", customkpicreator: "kpiCanvas" };
  const rows = () => resultAllRows(state.analysis || {});
  const isCsat = () => resultScoreName(state.analysis || {}) === "CSAT";
  const scoreLabel = () => isCsat() ? "CSAT" : "NPS";
  const typeOf = (row) => String(resultFirstValue(row, isCsat() ? ["CSAT Type", "CSAT Segment", "Satisfaction Segment"] : ["NPS Type", "NPS Segment"], "")).trim().toLowerCase();
  const sentimentOf = (row) => String(resultFirstValue(row, ["Sentiment", "Sentiment Label", "Overall Sentiment", "AI Sentiment"], "")).trim().toLowerCase();
  const dateOf = (row) => { const value = resultFirstValue(row, ["Feedback Date", "Survey Date", "Response Date", "Date"], ""); const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? null : parsed; };
  const monthKey = (row) => { const date = dateOf(row); return date ? `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}` : ""; };
  const monthLabel = (key) => { const [year, month] = String(key).split("-").map(Number); return year && month ? new Date(year, month - 1, 1).toLocaleString("en", { month: "short", year: "numeric" }) : key; };
  const dimensions = () => weeklyTrendDimensionColumns();
  const dimensionOptions = (includeOverall = true) => `${includeOverall ? '<option value="">Overall</option>' : ""}${dimensions().map((column) => `<option value="${escapeHtml(column)}">${escapeHtml(resultDimensionDisplayName(column) === column ? column : `${resultDimensionDisplayName(column)} (${column})`)}</option>`).join("")}`;
  const selectOptions = (values) => values.map(([value, label]) => `<option value="${escapeHtml(value)}">${escapeHtml(label)}</option>`).join("");
  const cleanRows = (source = rows()) => source.filter((row) => dateOf(row));
  const filterDimension = (source, dimension, value = "") => !dimension ? source : source.filter((row) => { const current = String(row?.[dimension] ?? "").trim(); return current && (!value || current === value); });
  const metricDefinitions = () => ({
    score: [scoreLabel(), "score"], volume: ["Survey Volume", "integer"], positivePct: [isCsat() ? "Satisfied %" : "Promoters %", "percent"],
    middlePct: [isCsat() ? "Neutral %" : "Passives %", "percent"], negativePct: [isCsat() ? "Dissatisfied %" : "Detractors %", "percent"],
    sentimentPositivePct: ["Positive Sentiment %", "percent"], sentimentNegativePct: ["Negative Sentiment %", "percent"],
  });
  function summarize(source) {
    const total = source.length; let positive = 0; let middle = 0; let negative = 0; let sentimentPositive = 0; let sentimentNegative = 0;
    source.forEach((row) => {
      const type = typeOf(row);
      if ((isCsat() && ["satisfied", "promoter"].includes(type)) || (!isCsat() && type === "promoter")) positive += 1;
      else if ((isCsat() && ["neutral", "passive"].includes(type)) || (!isCsat() && type === "passive")) middle += 1;
      else if ((isCsat() && ["dissatisfied", "detractor"].includes(type)) || (!isCsat() && type === "detractor")) negative += 1;
      const sentiment = sentimentOf(row); if (sentiment === "positive") sentimentPositive += 1; else if (sentiment === "negative") sentimentNegative += 1;
    });
    const pct = (value) => total ? value / total * 100 : 0;
    return { volume: total, positivePct: pct(positive), middlePct: pct(middle), negativePct: pct(negative), score: isCsat() ? pct(positive) : pct(positive) - pct(negative), sentimentPositivePct: pct(sentimentPositive), sentimentNegativePct: pct(sentimentNegative) };
  }
  function groupBy(source, keyFor) { const map = new Map(); source.forEach((row) => { const key = keyFor(row); if (!key) return; if (!map.has(key)) map.set(key, []); map.get(key).push(row); }); return map; }
  function metricPicker(selected = ["score", "volume"]) { const defs = metricDefinitions(); return Object.entries(defs).map(([key, [label]]) => `<label><input type="checkbox" data-studio-metric value="${key}" ${selected.includes(key) ? "checked" : ""}/><span>${escapeHtml(label)}</span></label>`).join(""); }
  function chartSvg(labels, series, type = "line", showLabels = false) {
    if (!labels.length || !series.length) return '<div class="studio-empty">No chartable values are available for this selection.</div>';
    const width = 1040, height = 410, left = 66, right = 66, top = 42, bottom = 70, plotW = width - left - right, plotH = height - top - bottom;
    const countSeries = series.filter((entry) => entry.format === "integer"), scoreSeries = series.filter((entry) => entry.format !== "integer");
    const scoreValues = scoreSeries.flatMap((entry) => entry.values).filter(Number.isFinite), countValues = countSeries.flatMap((entry) => entry.values).filter(Number.isFinite);
    let scoreMin = scoreValues.length ? Math.min(0, ...scoreValues) : 0, scoreMax = scoreValues.length ? Math.max(100, ...scoreValues) : 100;
    if (!isCsat() && scoreSeries.some((entry) => entry.key === "score")) { scoreMin = Math.min(-100, scoreMin); scoreMax = Math.max(100, scoreMax); }
    const countMax = Math.max(1, ...countValues, 1); const x = (index) => left + (labels.length === 1 ? plotW / 2 : index / (labels.length - 1) * plotW);
    const y = (value, count) => top + plotH - (count ? value / countMax : (value - scoreMin) / Math.max(scoreMax - scoreMin, 1)) * plotH;
    const grid = Array.from({ length: 5 }, (_, index) => { const ratio = index / 4, py = top + ratio * plotH; return `<line x1="${left}" y1="${py}" x2="${width - right}" y2="${py}"/><text x="${left - 10}" y="${py + 4}" text-anchor="end">${(scoreMax - ratio * (scoreMax - scoreMin)).toFixed(0)}</text>${countValues.length ? `<text x="${width - right + 10}" y="${py + 4}">${(countMax * (1 - ratio)).toFixed(0)}</text>` : ""}`; }).join("");
    const marks = series.map((entry, seriesIndex) => {
      const count = entry.format === "integer", color = colors[seriesIndex % colors.length];
      if (type === "bar") { const groupW = plotW / labels.length, barW = Math.max(4, Math.min(30, groupW / Math.max(series.length + 1, 2))); return entry.values.map((value, index) => { const px = left + index * groupW + groupW / 2 + (seriesIndex - (series.length - 1) / 2) * barW; const py = y(value, count); return `<rect x="${px - barW / 2}" y="${py}" width="${barW - 2}" height="${top + plotH - py}" rx="3" fill="${color}"><title>${escapeHtml(entry.label)}: ${Number(value).toFixed(2)}</title></rect>${showLabels ? `<text class="studio-data-label" x="${px}" y="${py - 6}" text-anchor="middle" style="fill:${color}">${Number(value).toFixed(2)}</text>` : ""}`; }).join(""); }
      const points = entry.values.map((value, index) => ({ x: x(index), y: y(value, count), value })).filter((point) => Number.isFinite(point.value)); const path = points.map((point, index) => `${index ? "L" : "M"}${point.x},${point.y}`).join(" ");
      return `<path class="studio-line ${count ? "count" : ""}" d="${path}" stroke="${color}"/>${points.map((point) => `<circle cx="${point.x}" cy="${point.y}" r="4" fill="${color}"><title>${escapeHtml(entry.label)}: ${Number(point.value).toFixed(2)}</title></circle>${showLabels ? `<text class="studio-data-label" x="${point.x}" y="${point.y + (seriesIndex % 2 ? 18 : -10)}" text-anchor="middle" style="fill:${color}">${Number(point.value).toFixed(2)}</text>` : ""}`).join("")}`;
    }).join("");
    const legend = series.map((entry, index) => `<g transform="translate(${left + (index % 5) * 175},${18 + Math.floor(index / 5) * 16})"><circle r="5" fill="${colors[index % colors.length]}"/><text x="10" y="4">${escapeHtml(entry.label)}</text></g>`).join("");
    const xLabels = labels.map((label, index) => `<text class="studio-x-label" x="${x(index)}" y="${height - 25}" text-anchor="middle">${escapeHtml(label)}</text>`).join("");
    return `<svg class="dashboard-studio-chart" viewBox="0 0 ${width} ${height}" role="img"><g class="studio-grid">${grid}</g>${legend}${marks}${xLabels}</svg>`;
  }
  function donutSvg(labels, values, showLabels) {
    const total = values.reduce((sum, value) => sum + value, 0) || 1; let angle = -90;
    const slices = values.map((value, index) => { const start = angle, delta = value / total * 360; angle += delta; const point = (degrees, radius = 120) => { const radians = degrees * Math.PI / 180; return [260 + Math.cos(radians) * radius, 190 + Math.sin(radians) * radius]; }; const [x1, y1] = point(start), [x2, y2] = point(angle); const large = delta > 180 ? 1 : 0; return `<path d="M260 190 L${x1} ${y1} A120 120 0 ${large} 1 ${x2} ${y2} Z" fill="${colors[index % colors.length]}"><title>${escapeHtml(labels[index])}: ${value.toFixed(2)}</title></path>`; }).join("");
    const legend = labels.map((label, index) => `<g transform="translate(520,${45 + index * 27})"><rect width="13" height="13" rx="3" fill="${colors[index % colors.length]}"/><text x="21" y="11">${escapeHtml(label)}${showLabels ? ` · ${values[index].toFixed(2)}` : ""}</text></g>`).join("");
    return `<svg class="dashboard-studio-chart studio-donut" viewBox="0 0 900 380"><g>${slices}<circle cx="260" cy="190" r="66" fill="#fff"/><text x="260" y="184" text-anchor="middle" class="studio-donut-total">${total.toFixed(2)}</text><text x="260" y="207" text-anchor="middle">Total</text></g>${legend}</svg>`;
  }
  const table = (headers, body, graphRows = true) => `<div class="weekly-trend-table-wrap"><table class="weekly-trend-table studio-table"><thead><tr>${headers.map((header) => `<th>${escapeHtml(header)}</th>`).join("")}</tr></thead><tbody>${body.map((row) => `<tr>${row.map((cell, index) => `<${index ? "td" : "th"}>${index || !graphRows ? escapeHtml(cell) : `<div class="weekly-trend-row-label studio-table-row-label">${chartButton(`Graph ${cell}`)}<span>${escapeHtml(cell)}</span></div>`}</${index ? "td" : "th"}>`).join("")}</tr>`).join("")}</tbody></table></div>`;
  function chartButton(label = "Open graph") { return `<button class="weekly-trend-row-chart studio-open-chart" data-studio-open-chart type="button" title="${escapeHtml(label)}" aria-label="${escapeHtml(label)}"><svg viewBox="0 0 20 20"><path d="M3 16h14M5 13l3-4 3 2 4-6"/></svg></button>`; }
  function chartCard(title, subtitle, chart, tableMarkup = "") { return `<article class="weekly-trend-card studio-result-card"><div class="weekly-trend-card-head"><div><h3>${escapeHtml(title)}</h3><p>${escapeHtml(subtitle)}</p></div><div class="studio-card-actions">${chartButton(`Graph ${title}`)}<button class="button button-secondary button-compact" data-studio-snapshot type="button">Snapshot PNG</button></div></div><div class="studio-chart-source" hidden>${chart}</div>${tableMarkup}</article>`; }
  function snapshot(button) { const svg = button.closest(".studio-result-card,.studio-kpi-tile")?.querySelector("svg"); if (!svg) return; const clone = svg.cloneNode(true); clone.setAttribute("xmlns", "http://www.w3.org/2000/svg"); const style = document.createElementNS("http://www.w3.org/2000/svg", "style"); style.textContent = `text{fill:#5c7488;font:11px 'Segoe UI',Arial,sans-serif}.studio-grid line{stroke:#dce6ec}.studio-line{fill:none;stroke-width:3}.studio-line.count{stroke-dasharray:7 5}.studio-data-label{font-size:9px;font-weight:800;paint-order:stroke;stroke:#fff;stroke-width:3px}`; clone.insertBefore(style, clone.firstChild); const url = URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(clone)], { type: "image/svg+xml" })); const image = new Image(); image.onload = () => { const canvas = document.createElement("canvas"); canvas.width = 2080; canvas.height = 820; const context = canvas.getContext("2d"); context.fillStyle = "#fff"; context.fillRect(0, 0, canvas.width, canvas.height); context.drawImage(image, 0, 0, canvas.width, canvas.height); URL.revokeObjectURL(url); const link = document.createElement("a"); link.download = "custom-dashboard-chart.png"; link.href = canvas.toDataURL("image/png"); link.click(); }; image.src = url; }
  function openChart(button) {
    const card = button.closest(".studio-result-card,.studio-kpi-tile"); const source = card?.querySelector(".studio-chart-source"); if (!source) return;
    let overlay = document.getElementById("dashboardStudioChartOverlay");
    if (!overlay) { overlay = document.createElement("div"); overlay.id = "dashboardStudioChartOverlay"; overlay.className = "weekly-trend-chart-overlay"; document.body.appendChild(overlay); }
    const title = card.querySelector("h3")?.textContent || "Custom Dashboard Graph";
    overlay.innerHTML = `<div class="weekly-trend-chart-dialog"><div class="weekly-trend-chart-head"><div><span>Dashboard Maker · Interactive Graph</span><h2>${escapeHtml(title)}</h2></div><button class="studio-chart-close" data-studio-close-chart type="button" aria-label="Close graph">×</button></div><div class="weekly-trend-chart-stage">${source.innerHTML}</div></div>`;
    overlay.classList.add("open");
    overlay.querySelector("[data-studio-close-chart]")?.addEventListener("click", () => overlay.classList.remove("open"));
    overlay.addEventListener("click", (event) => { if (event.target === overlay) overlay.classList.remove("open"); }, { once: true });
  }
  function commonToggle() { return `<label class="studio-toggle"><input data-studio-labels type="checkbox"/><span></span><b>Data labels</b></label>`; }
  function shell(title, description, controls, extras = "") { return `<div class="weekly-trend-builder studio-builder"><div class="weekly-trend-builder-head"><h3>${escapeHtml(title)}</h3><p>${escapeHtml(description)}</p></div><div class="studio-controls">${controls}</div>${extras}<div class="weekly-trend-actions"><button class="button button-secondary" data-studio-preview type="button">Preview</button><button class="button button-primary" data-studio-add type="button">Add Dashboard</button></div><div class="summary-builder-message" data-studio-message>${rows().length.toLocaleString()} analyzed rows available.</div><section class="studio-preview-panel" data-studio-preview-panel><div class="studio-preview-label">Dashboard Preview</div><div class="weekly-trend-preview" data-studio-output><div class="weekly-trend-empty">Select Preview to review the current configuration before adding it.</div></div></section></div><div class="panel studio-added-panel"><div class="panel-title-row"><div><h2>Added Dashboards</h2><p class="panel-meta" data-studio-added-meta>No dashboards added yet.</p></div><button class="button button-secondary" data-studio-clear type="button">Clear</button></div><div class="weekly-trend-dashboard-output" data-studio-added></div></div>`; }
  function dimensionValueOptions(dimension) { return Array.from(new Set(rows().map((row) => String(row?.[dimension] ?? "").trim()).filter(Boolean))).sort().map((value) => `<option value="${escapeHtml(value)}">${escapeHtml(value)}</option>`).join(""); }
  function renderMonthlyTrend(host) {
    host.innerHTML = shell("Monthly Trend Builder", "Compare one or more customer-experience measures month by month.", `<label>Months<select data-field="months">${selectOptions([["6","Last 6 months"],["12","Last 12 months"],["0","All months"]])}</select></label><label>Dimension<select data-field="dimension">${dimensionOptions()}</select></label><label>Dimension Value<select data-field="dimensionValue"><option value="">All values</option></select></label><label>Chart Type<select data-field="chartType">${selectOptions([["line","Line chart"],["bar","Bar chart"]])}</select></label>${commonToggle()}`, `<div class="weekly-trend-metric-picker"><div><strong>Graph Metrics</strong><span>Select one or more series.</span></div><div class="weekly-trend-metric-options">${metricPicker()}</div></div>`);
  }
  function previewMonthlyTrend(host) {
    const dimension = host.querySelector('[data-field="dimension"]').value, value = host.querySelector('[data-field="dimensionValue"]').value, limit = Number(host.querySelector('[data-field="months"]').value), selected = [...host.querySelectorAll("[data-studio-metric]:checked")].map((input) => input.value);
    const source = filterDimension(cleanRows(), dimension, value), groups = groupBy(source, monthKey); let keys = [...groups.keys()].sort(); if (limit) keys = keys.slice(-limit); const defs = metricDefinitions(); const series = selected.map((key) => ({ key, label: defs[key][0], format: defs[key][1], values: keys.map((month) => summarize(groups.get(month))[key]) }));
    const chart = chartSvg(keys.map(monthLabel), series, host.querySelector('[data-field="chartType"]').value, host.querySelector("[data-studio-labels]").checked); const body = series.map((entry) => [entry.label, ...entry.values.map((number) => Number(number).toFixed(2))]); host.querySelector("[data-studio-output]").innerHTML = chartCard(`Monthly ${scoreLabel()} Trend`, dimension ? `${dimension}: ${value || "All values"}` : "Overall", chart, table(["Metric", ...keys.map(monthLabel)], body));
  }
  function renderMonthlyMatrix(host) { const months = [...new Set(cleanRows().map(monthKey).filter(Boolean))].sort().reverse(); host.innerHTML = shell("Monthly Dimension Matrix Builder", "Place dimension values across a selected reporting month and graph any supported metric.", `<label>Reporting Month<select data-field="month">${months.map((key) => `<option value="${key}">${monthLabel(key)}</option>`).join("")}</select></label><label>Dimension<select data-field="dimension">${dimensionOptions(false)}</select></label><label>Metric<select data-field="metric">${Object.entries(metricDefinitions()).map(([key,[label]]) => `<option value="${key}">${escapeHtml(label)}</option>`).join("")}</select></label><label>Maximum Values<select data-field="limit">${selectOptions([["10","Top 10"],["15","Top 15"],["25","Top 25"],["0","All"]])}</select></label><label>Chart Type<select data-field="chartType">${selectOptions([["bar","Bar chart"],["line","Line chart"]])}</select></label>${commonToggle()}`); }
  function previewMonthlyMatrix(host) { const month = host.querySelector('[data-field="month"]').value, dimension = host.querySelector('[data-field="dimension"]').value, metric = host.querySelector('[data-field="metric"]').value, limit = Number(host.querySelector('[data-field="limit"]').value), defs = metricDefinitions(); const groups = groupBy(cleanRows().filter((row) => monthKey(row) === month), (row) => String(row?.[dimension] ?? "").trim()); let items = [...groups.entries()].map(([label, source]) => ({ label, volume: source.length, value: summarize(source)[metric] })).sort((a,b) => b.volume-a.volume); if (limit) items = items.slice(0,limit); const series = [{ key: metric, label: defs[metric][0], format: defs[metric][1], values: items.map((item) => item.value) }]; host.querySelector("[data-studio-output]").innerHTML = chartCard(`${dimension} · ${monthLabel(month)}`, `${items.length} values shown`, chartSvg(items.map((item) => item.label), series, host.querySelector('[data-field="chartType"]').value, host.querySelector("[data-studio-labels]").checked), table([dimension, defs[metric][0], "Survey Volume"], items.map((item) => [item.label, item.value.toFixed(2), String(item.volume)]))); }
  function renderPerformance(host) { host.innerHTML = shell("Performance & Coaching Builder", "Apply minimum-sample and target guardrails to an agent, manager, or other business dimension.", `<label>Performance Dimension<select data-field="dimension">${dimensionOptions(false)}</select></label><label>Target Score<input data-field="target" type="number" value="${isCsat() ? 80 : 20}" step="0.1"/></label><label>Minimum Surveys<input data-field="minimum" type="number" value="5" min="1"/></label><label>Maximum Entities<select data-field="limit">${selectOptions([["10","Top 10"],["20","Top 20"],["0","All reliable entities"]])}</select></label><label>Chart Type<select data-field="chartType">${selectOptions([["bar","Bar chart"],["line","Line chart"]])}</select></label>${commonToggle()}`); }
  function previewPerformance(host) { const dimension = host.querySelector('[data-field="dimension"]').value, target = Number(host.querySelector('[data-field="target"]').value), minimum = Number(host.querySelector('[data-field="minimum"]').value), limit = Number(host.querySelector('[data-field="limit"]').value); const groups = groupBy(rows(), (row) => String(row?.[dimension] ?? "").trim()); let items = [...groups.entries()].map(([label, source]) => ({ label, ...summarize(source) })).filter((item) => item.volume >= minimum).sort((a,b) => b.score-a.score); if (limit) items = items.slice(0,limit); const series = [{ key:"score", label:scoreLabel(), format:"score", values:items.map((item)=>item.score) }]; const body = items.map((item) => [item.label, item.score.toFixed(2), String(item.volume), item.score >= target ? "Replication / strong" : item.score >= target - 10 ? "Monitor" : "Coaching priority"]); host.querySelector("[data-studio-output]").innerHTML = chartCard(`${dimension} Performance & Coaching`, `Target ${target.toFixed(2)} · minimum ${minimum} surveys`, chartSvg(items.map((item)=>item.label), series, host.querySelector('[data-field="chartType"]').value, host.querySelector("[data-studio-labels]").checked), table([dimension, scoreLabel(), "Surveys", "Recommended population"], body)); }
  function driverColumns() { const preferred = ["ACPT Primary Category","Primary Reason","Bucket Category","Theme","Owl Primary Driver","Owl Issue Type"]; const available = new Set(rows().slice(0,500).flatMap((row)=>Object.keys(row||{}))); return preferred.filter((column)=>available.has(column)); }
  function renderDrivers(host) { host.innerHTML = shell("Drivers & Sentiment Builder", "Rank customer-experience drivers and optionally focus on a score or sentiment segment.", `<label>Driver Field<select data-field="driver">${driverColumns().map((column)=>`<option>${escapeHtml(column)}</option>`).join("")}</select></label><label>Population<select data-field="population">${selectOptions([["all","All surveys"],["positive","Positive score segment"],["middle","Middle score segment"],["negative","Negative score segment"],["negativeSentiment","Negative sentiment"]])}</select></label><label>Measure<select data-field="measure">${selectOptions([["count","Survey count"],["percent","Share of selected population"]])}</select></label><label>Top Drivers<select data-field="limit">${selectOptions([["5","Top 5"],["10","Top 10"],["15","Top 15"]])}</select></label><label>Chart Type<select data-field="chartType">${selectOptions([["bar","Bar chart"],["donut","Donut chart"]])}</select></label>${commonToggle()}`); }
  function previewDrivers(host) { const driver = host.querySelector('[data-field="driver"]').value, population = host.querySelector('[data-field="population"]').value, measure = host.querySelector('[data-field="measure"]').value, limit = Number(host.querySelector('[data-field="limit"]').value); let source = rows(); if (population !== "all") source = source.filter((row) => { if (population === "negativeSentiment") return sentimentOf(row)==="negative"; const type=typeOf(row); if (population==="positive") return isCsat()?["satisfied","promoter"].includes(type):type==="promoter"; if(population==="middle") return isCsat()?["neutral","passive"].includes(type):type==="passive"; return isCsat()?["dissatisfied","detractor"].includes(type):type==="detractor"; }); const groups=groupBy(source,(row)=>String(row?.[driver]??"").trim()); const total=source.length||1; const items=[...groups.entries()].map(([label,group])=>({label,value:measure==="percent"?group.length/total*100:group.length,volume:group.length})).sort((a,b)=>b.value-a.value).slice(0,limit); const labels=items.map((item)=>item.label), values=items.map((item)=>item.value), chart=host.querySelector('[data-field="chartType"]').value==="donut"?donutSvg(labels,values,host.querySelector("[data-studio-labels]").checked):chartSvg(labels,[{key:"driver",label:measure==="percent"?"Share %":"Survey Count",format:measure==="percent"?"percent":"integer",values}],"bar",host.querySelector("[data-studio-labels]").checked); host.querySelector("[data-studio-output]").innerHTML=chartCard(`${driver} Drivers`,`${source.length.toLocaleString()} selected surveys`,chart,table([driver,measure==="percent"?"Share %":"Count"],items.map((item)=>[item.label,item.value.toFixed(2)]))); }
  function renderKpi(host) { host.innerHTML = shell("Custom KPI Canvas Builder", "Add KPI, monthly line, or dimension bar tiles to a flexible canvas.", `<label>Tile Title<input data-field="title" value="Customer Experience KPI"/></label><label>Tile Type<select data-field="tileType">${selectOptions([["kpi","KPI card"],["line","Monthly line chart"],["bar","Dimension bar chart"]])}</select></label><label>Metric<select data-field="metric">${Object.entries(metricDefinitions()).map(([key,[label]])=>`<option value="${key}">${escapeHtml(label)}</option>`).join("")}</select></label><label>Dimension<select data-field="dimension">${dimensionOptions()}</select></label><label>Top Values<select data-field="limit">${selectOptions([["5","Top 5"],["10","Top 10"],["15","Top 15"]])}</select></label>${commonToggle()}`); renderKpiTiles(host); }
  function configurationSignature(host, kind) {
    const values = [...host.querySelectorAll("[data-field], [data-studio-metric], [data-studio-labels]")].map((control) => [control.dataset.field || control.value || control.type, control.type === "checkbox" ? control.checked : control.value]);
    return JSON.stringify([kind, values]);
  }
  function kpiConfig(host) { return {id:`kpi-${Date.now()}`,signature:configurationSignature(host,"kpiCanvas"),title:host.querySelector('[data-field="title"]').value||"KPI",tileType:host.querySelector('[data-field="tileType"]').value,metric:host.querySelector('[data-field="metric"]').value,dimension:host.querySelector('[data-field="dimension"]').value||dimensions()[0]||"",limit:Number(host.querySelector('[data-field="limit"]').value),labels:host.querySelector("[data-studio-labels]").checked}; }
  function kpiMarkup(tile, removable = false) { const defs=metricDefinitions(), overall=summarize(rows()), label=defs[tile.metric][0]; let content="", graph=false; if(tile.tileType==="kpi") content=`<div class="studio-big-kpi"><strong>${Number(overall[tile.metric]).toFixed(2)}${defs[tile.metric][1]==="percent"?"%":""}</strong><span>${escapeHtml(label)}</span></div>`; else if(tile.tileType==="line"){const groups=groupBy(cleanRows(),monthKey),keys=[...groups.keys()].sort().slice(-12);content=chartSvg(keys.map(monthLabel),[{key:tile.metric,label,format:defs[tile.metric][1],values:keys.map((key)=>summarize(groups.get(key))[tile.metric])}],"line",tile.labels);graph=true;}else{const groups=groupBy(rows(),(row)=>String(row?.[tile.dimension]??"").trim());const items=[...groups.entries()].map(([name,source])=>({name,value:summarize(source)[tile.metric],volume:source.length})).sort((a,b)=>b.volume-a.volume).slice(0,tile.limit);content=chartSvg(items.map((item)=>item.name),[{key:tile.metric,label,format:defs[tile.metric][1],values:items.map((item)=>item.value)}],"bar",tile.labels);graph=true;} return `<article class="studio-kpi-tile"><div class="studio-kpi-head"><h3>${escapeHtml(tile.title)}</h3><div>${graph?chartButton(`Graph ${tile.title}`):""}${graph?'<button data-studio-snapshot type="button">Snapshot</button>':""}${removable?`<button data-remove-kpi="${tile.id}" type="button">×</button>`:""}</div></div>${graph?`<div class="studio-chart-source" hidden>${content}</div><div class="studio-graph-hint">Use the graph button to open the interactive chart.</div>`:content}</article>`; }
  function previewKpi(host) { host.querySelector("[data-studio-output]").innerHTML=`<div class="studio-kpi-canvas">${kpiMarkup(kpiConfig(host))}</div>`; }
  function addKpi(host) { const config=kpiConfig(host); if(studioState.kpiTiles.some((tile)=>tile.signature===config.signature))return false; studioState.kpiTiles.push(config); renderKpiTiles(host); return true; }
  function renderKpiTiles(host) { const output=host.querySelector("[data-studio-added]"); if(!output)return; output.innerHTML=studioState.kpiTiles.length?`<div class="studio-kpi-canvas">${studioState.kpiTiles.map((tile)=>kpiMarkup(tile,true)).join("")}</div>`:'<div class="weekly-trend-empty">No dashboards added yet.</div>'; const meta=host.querySelector("[data-studio-added-meta]"); if(meta)meta.textContent=studioState.kpiTiles.length?`${studioState.kpiTiles.length} dashboard${studioState.kpiTiles.length===1?"":"s"} added.`:"No dashboards added yet."; }
  function createPreview(host, kind) { if(kind==="monthlyTrend")previewMonthlyTrend(host);else if(kind==="monthlyMatrix")previewMonthlyMatrix(host);else if(kind==="performanceCoaching")previewPerformance(host);else if(kind==="driversSentiment")previewDrivers(host);else previewKpi(host); }
  function renderAdded(host, kind) { if(kind==="kpiCanvas"){renderKpiTiles(host);return;} const definitions=studioState.dashboards[kind]||[], output=host.querySelector("[data-studio-added]"); output.innerHTML=definitions.length?definitions.map((item)=>`<div class="studio-added-dashboard"><button class="studio-remove-dashboard" data-studio-remove="${item.id}" type="button">Remove</button>${item.markup}</div>`).join(""):'<div class="weekly-trend-empty">No dashboards added yet.</div>'; const meta=host.querySelector("[data-studio-added-meta]"); if(meta)meta.textContent=definitions.length?`${definitions.length} dashboard${definitions.length===1?"":"s"} added.`:"No dashboards added yet."; }
  function wire(host, kind) { host.addEventListener("change", (event)=>{ if(event.target.matches('[data-field="dimension"]')){const valueSelect=host.querySelector('[data-field="dimensionValue"]');if(valueSelect)valueSelect.innerHTML='<option value="">All values</option>'+dimensionValueOptions(event.target.value);} }); host.addEventListener("click",(event)=>{const graphButton=event.target.closest("[data-studio-open-chart]");if(graphButton){openChart(graphButton);return;}const snapshotButton=event.target.closest("[data-studio-snapshot]");if(snapshotButton){snapshot(snapshotButton);return;}const remove=event.target.closest("[data-remove-kpi]");if(remove){studioState.kpiTiles=studioState.kpiTiles.filter((tile)=>tile.id!==remove.dataset.removeKpi);renderKpiTiles(host);return;}const removeDashboard=event.target.closest("[data-studio-remove]");if(removeDashboard){studioState.dashboards[kind]=(studioState.dashboards[kind]||[]).filter((item)=>item.id!==removeDashboard.dataset.studioRemove);renderAdded(host,kind);return;}if(event.target.closest("[data-studio-clear]")){if(kind==="kpiCanvas")studioState.kpiTiles=[];else studioState.dashboards[kind]=[];renderAdded(host,kind);return;}const preview=event.target.closest("[data-studio-preview]"), add=event.target.closest("[data-studio-add]");if(!preview&&!add)return; const actionButton=add||preview; if(actionButton.disabled)return; actionButton.disabled=true; try{createPreview(host,kind);const previewPanel=host.querySelector("[data-studio-preview-panel]");previewPanel?.classList.add("has-preview");if(preview){host.querySelector("[data-studio-message]").textContent="Preview refreshed from the current analyzed rows. Nothing has been added yet.";previewPanel?.scrollIntoView({behavior:"smooth",block:"nearest"});return;}const signature=configurationSignature(host,kind);let added=false;if(kind==="kpiCanvas")added=addKpi(host);else if(!(studioState.dashboards[kind]||[]).some((item)=>item.signature===signature)){const markup=host.querySelector("[data-studio-output]").innerHTML;studioState.dashboards[kind].push({id:`studio-${Date.now()}`,markup,signature});renderAdded(host,kind);added=true;}host.querySelector("[data-studio-message]").textContent=added?"Dashboard added from the current analyzed rows.":"This dashboard configuration has already been added. Change an option before adding another.";}catch(error){host.querySelector("[data-studio-message]").textContent=error.message||"Unable to build this dashboard.";}finally{actionButton.disabled=false;}}); }
  window.refreshDashboardMakerStudio = (viewId) => { const kind=viewKinds[viewId]||viewId; const host=document.querySelector(`[data-dashboard-studio="${kind}"]`); if(!host)return; if(!rows().length){host.innerHTML='<div class="weekly-trend-empty">Run an analysis before using this creator.</div>';return;} if(host.dataset.ready==="1")return; if(kind==="monthlyTrend")renderMonthlyTrend(host);else if(kind==="monthlyMatrix")renderMonthlyMatrix(host);else if(kind==="performanceCoaching")renderPerformance(host);else if(kind==="driversSentiment")renderDrivers(host);else renderKpi(host); wire(host,kind); renderAdded(host,kind); host.dataset.ready="1"; };
})();
